### ISSUE TITLE
Windowsバージョンが起動しない！

### ISSUE THREAD

**Issue by ryotayama** [arigayas/test#2]
## 環境情報
- OS: 'Windows 10 Home'
- 聞々ハヤえもんVer: '2.76'

## バグ内容
起動しようとしたら起動しません！

## 再現手順
該当バグの再現手順を記述ください。
1.Hayaemon.exeを起動
2.「bass.dllが見つかりません」というエラーが出る。

### 期待する動作
起動してほしい。

## 再現頻度
必ず起動しない。

**Comment by arigayas** [comment]
何年も開いたままだったので閉じます。
