### ISSUE TITLE
Title!

### ISSUE THREAD

**Issue by ryutaro** [arigayas/test#3]
## 環境情報
- OS: Microsoft Windows 10 Pro for workstation V1803B17134.112
- 聞々ハヤえもんVer: バージョン問わず
- PC情報: 
------------------
System Information
------------------
      Time of this report: 7/1/2018, 20:05:25
             Machine name: **********
               Machine Id: **********
         Operating System: Windows 10 Pro for Workstations 64-bit (10.0, Build 17134) (17134.rs4_release.180410-1804)
                 Language: Japanese (Regional Setting: Japanese)
      System Manufacturer: **********
             System Model: All Series
                     BIOS: 4649 (type: UEFI)
                Processor: Intel(R) Xeon(TM) CPU E7-8860 v3 @ 2.20GHz (32 CPUs), ~2.2GHz
                   Memory: 65536MB RAM
      Available OS Memory: 65402MB RAM
                Page File: 21800MB used, 5151MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.17134.0001 64bit Unicode

------------
DxDiag Notes
------------
      Display Tab 1: No problems found.
        Sound Tab 1: No problems found.
        Sound Tab 2: No problems found.
          Input Tab: No problems found.

--------------------
DirectX Debug Levels
--------------------
Direct3D:    0/4 (retail)
DirectDraw:  0/4 (retail)
DirectInput: 0/5 (retail)
DirectMusic: 0/5 (retail)
DirectPlay:  0/9 (retail)
DirectSound: 0/5 (retail)
DirectShow:  0/6 (retail)

---------------
Display Devices
---------------
           Card name: NVIDIA Quadro P6000
        Manufacturer: NVIDIA
           Chip type: Quadro P6000
            DAC type: Integrated RAMDAC
         Device Type: Full Device (POST)
          Device Key: **********
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 20360 MB
    Dedicated Memory: 4043 MB
       Shared Memory: 16316 MB
        Current Mode: 3840 x 2160 (32 bit) (60Hz)
         HDR Support: Not Supported
    Display Topology: External
 Display Color Space: DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
     Color Primaries: Red(0.638195,0.330578), Green(0.312023,0.623547), Blue(0.150891,0.068859), White Point(0.313977,0.329602)
   Display Luminance: Min Luminance = 0.500000, Max Luminance = 270.000000, MaxFullFrameLuminance = 270.000000
        Monitor Name: Generic PnP Monitor
       Monitor Model: **********
          Monitor Id: **********
         Native Mode: 3840 x 2160(p) (60.000Hz)
         Output Type: DVI
Monitor Capabilities: HDR
Display Pixel Format: DISPLAYCONFIG_PIXELFORMAT_32BPP
      Advanced Color: Not Supported
         Driver Name: **********
 Driver File Version: 24.21.0013.9811 (English)
      Driver Version: 24.21.13.9811
         DDI Version: 12
      Feature Levels: 12_1,12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
        Driver Model: WDDM 2.4
 Graphics Preemption: DMA
  Compute Preemption: DMA
            Miracast: Not Supported
 Hybrid Graphics GPU: Not Supported
      Power P-states: Not Supported
      Virtualization: Paravirtualization 
          Block List: No Blocks
  Catalog Attributes: Universal:False Declarative:False 
   Driver Attributes: Final Retail
    Driver Date/Size: 2018/06/01 9:00:00, 950744 bytes
         WHQL Logo'd: Yes
     WHQL Date Stamp: Unknown
   Device Identifier: **********
           Vendor ID: 0x10DE
           Device ID: **********
           SubSys ID: **********
         Revision ID: **********
  Driver Strong Name: **********
      Rank Of Driver: **********
         Video Accel: 
         DXVA2 Modes: DXVA2_ModeMPEG2_VLD  DXVA2_ModeVC1_D2010  DXVA2_ModeVC1_VLD  DXVA2_ModeH264_VLD_Stereo_Progressive_NoFGT  DXVA2_ModeH264_VLD_Stereo_NoFGT  DXVA2_ModeH264_VLD_NoFGT  DXVA2_ModeHEVC_VLD_Main  DXVA2_ModeMPEG4pt2_VLD_Simple  DXVA2_ModeMPEG4pt2_VLD_AdvSimple_NoGMC  

## バグ内容
Media Foundationに対応していない

## 再現手順
起動するだけ

### 期待する動作
起動時にMedia Foundation APIを初期化する

## 再現頻度
絶対的

## スクリーンショット
data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==

**Comment by ryutaro** [comment]
プップー通りまーす:rocket:

**Comment by arigayas** [comment]
@ryutaro 自由すぎるだろwwww

**Comment by ryutaro** [comment]
DxDiagそのまま貼るとどうなるのかを見たかったってのが半分ある

**Comment by arigayas** [comment]
なるほどね。
